import type { StorageProfile } from "./types";

export const STORAGE_PROFILES: StorageProfile[] = [
  {
    id: "fortigate-raw-only",
    name: "Fortigate 원문만 보관",
    group: "Fortigate / 방화벽 계열",
    labCase: "ldb.syn.zstd.p1",
    storageRatio: 0.191,
    description: "긴 KV 원문 로그를 가장 작게 보관하는 후보",
    flags: [],
  },
  {
    id: "fortigate-raw-parsed-recommended",
    name: "Fortigate 원문+파싱 보관",
    group: "Fortigate / 방화벽 계열",
    labCase: "ldb.syn.zstd.p2",
    storageRatio: 0.462,
    description: "원문 보존과 ECS/parsed 필드 검색을 모두 가져가는 권장 균형안",
    flags: [],
  },
  {
    id: "fortigate-parsed-only",
    name: "Fortigate 파싱만 보관",
    group: "Fortigate / 방화벽 계열",
    labCase: "ldb.syn.zstd.p3",
    storageRatio: 0.295,
    description: "원문 검색이 필요 없고 parsed 필드 중심으로 운영하는 후보",
    flags: ["parsed_only"],
  },
  {
    id: "web-raw-only",
    name: "Web 원문만 보관",
    group: "웹 액세스 로그",
    labCase: "ldb.syn.zstd.p1",
    storageRatio: 0.266,
    description: "웹 로그 원문 보관 후보",
    flags: [],
  },
  {
    id: "web-raw-parsed",
    name: "Web 원문+파싱 보관",
    group: "웹 액세스 로그",
    labCase: "ldb.syn.zstd.p2",
    storageRatio: 0.429,
    description: "원문과 parsed 필드를 함께 유지하는 후보",
    flags: [],
  },
  {
    id: "web-parsed-only",
    name: "Web 파싱만 보관",
    group: "웹 액세스 로그",
    labCase: "ldb.syn.zstd.p3",
    storageRatio: 0.254,
    description: "웹 액세스 로그의 저장 효율 중심 후보",
    flags: ["parsed_only"],
  },
  {
    id: "snmp-tsds-parsed-only",
    name: "SNMP TSDS 파싱만 보관",
    group: "메트릭/SNMP/시계열",
    labCase: "tsds.syn.zstd.p3",
    storageRatio: 0.335,
    description: "메트릭/시계열 데이터의 우선 후보",
    flags: ["parsed_only", "tsds"],
  },
  {
    id: "snmp-logsdb-raw-only",
    name: "SNMP logsdb 원문만 보관",
    group: "메트릭/SNMP/시계열",
    labCase: "ldb.syn.zstd.p1",
    storageRatio: 0.406,
    description: "TSDS를 적용하지 못하고 원문 보관이 필요한 경우의 대안",
    flags: [],
  },
  {
    id: "snmp-logsdb-parsed-only",
    name: "SNMP logsdb 파싱만 보관",
    group: "메트릭/SNMP/시계열",
    labCase: "ldb.syn.zstd.p3",
    storageRatio: 0.557,
    description: "TSDS를 적용하지 못하는 메트릭성 데이터의 보수 대안",
    flags: ["parsed_only"],
  },
];
